package gateway

// routes mirrors the registered non-admin Convey API. Tests enforce inventory parity.
var routes = map[string][]string{
	"DELETE": {
		"/v1/sandbox/messages",
		"/v1/suppressions/:id",
		"/v1/webhook-subscriptions/:id",
	},
	"GET": {
		"/v1/auth/session",
		"/v1/batches",
		"/v1/batches/:batchId",
		"/v1/dlq",
		"/v1/messages/:messageId",
		"/v1/messages/:messageId/timeline",
		"/v1/messages/:messageId/trace",
		"/v1/sandbox/messages",
		"/v1/suppressions",
		"/v1/t/:token",
		"/v1/templates",
		"/v1/templates/:slug",
		"/v1/templates/partials",
		"/v1/webhook-subscriptions",
		"/v1/webhooks/:provider",
		"/v1/webhooks/:provider/inbound",
		"/v1/webhooks/:provider/incoming",
		"/v1/webhooks/:provider/status",
	},
	"POST": {
		"/v1/batches",
		"/v1/batches/:batchId/cancel",
		"/v1/batches/:batchId/pause",
		"/v1/batches/:batchId/resume",
		"/v1/dlq/replay",
		"/v1/dlq/replay-mutated",
		"/v1/messages",
		"/v1/messages/bulk",
		"/v1/messages/templates/preview",
		"/v1/receipts",
		"/v1/suppressions",
		"/v1/suppressions/bulk",
		"/v1/templates",
		"/v1/templates/:slug/publish",
		"/v1/templates/:slug/versions",
		"/v1/templates/partials",
		"/v1/templates/render",
		"/v1/webhook-subscriptions",
		"/v1/webhook-subscriptions/:id/test",
		"/v1/webhooks/:provider",
		"/v1/webhooks/:provider/inbound",
		"/v1/webhooks/:provider/incoming",
		"/v1/webhooks/:provider/status",
	},
}
